Update shellcheck.yml

diff --git a/.github/workflows/shellcheck.yml b/.github/workflows/shellcheck.yml
--- a/.github/workflows/shellcheck.yml
+++ b/.github/workflows/shellcheck.yml
@@ -1,12 +1,12 @@
 name: ShellCheck
 
 on:
-  push:
-    branches:
-      - '**'
   pull_request:
     branches:
-      - '**'
+      - 'main'
+      - 'master'
+    types: [ opened, synchronize ]
+      
 
 jobs:
   shellcheck:
@@ -33,6 +33,70 @@ jobs:
         else
           # For pushes, get the diff between HEAD and the previous commit
           if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
+            git diff --name-only HEAD^ HEAD | grep '\.sh$' > scripts-to-check.txt
+          else
+            # If HEAD^ is not available (e.g., first commit), list all shell scripts
+            git ls-files | grep '\.sh$' > scripts-to-check.txt
+          fi
+        fi
+
+        # Check if any scripts were found
+        if [ ! -s scripts-to-check.txt ]; then
+          echo "No shell scripts to check."
+          exit 0
+        fi
+
+
+#====================================================================================================#
+#                                           shellcheck                                               #  
+#====================================================================================================#
+
+    - name: Run ShellCheck
+      run: |
+        while IFS= read -r script; do
+          echo "Checking $script"
+          shellcheck "$script" || exit 1
+        done < scripts-to-check.txt
+
+    - name: Annotate ShellCheck results
+      id: shellcheck_test
+      if: success() || failure()
+      run: |
+        output_file="${{ github.workspace }}/shellcheck_results.md"
+        : > $output_file  # Create the file or clear it if it already exists
+        while IFS= read -r script; do
+          echo "Checking $script" >> $output_file
+          shellcheck "$script" >> $output_file || true
+        done < scripts-to-check.txt
+
+    - name: Create ShellCheck report
+      if: failure()
+      run: |
+        output_file="${{ github.workspace }}/shellcheck_report.md"
+        {
+          echo '<details><summary>❌ ShellCheck failed checks report</summary>'
+          echo ''
+          echo '```'
+          cat "${{ github.workspace }}/shellcheck_results.md"
+          echo '```'
+          echo ''
+          echo '</details>'
+        } > $output_file
+        cat $output_file
+
+#====================================================================================================#
+#                                  PR Report Comment                                                 #  
+#====================================================================================================#   
+    - name: Comment PR actions message
+      uses: mshick/add-pr-comment@v2
+      if: failure()
+      with:
+        message-path: |
+          ${{ github.workspace }}/shellcheck_report.md
+        issue: ${{ github.event.pull_request.number }}
+        refresh-message-position: true
+        allow-repeats: false
+        message-success: ✅ Linted files successfully  
             git diff --name-only HEAD^ HEAD | grep '\.sh$' > scripts-to-check.txt
           else
             # If HEAD^ is not available (e.g., first commit), list all shell scripts
